name: avis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - ray[rllib]==2.1.0
      - gymnasium[classic-control]==0.28.1
      - torch>=2.0.0
      - psutil
      - matplotlib
      - pandas
